import type { Metadata } from "next";

import "./globals.scss";
import biotif from "./font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={biotif.className}>{children}</body>
    </html>
  );
}
